testing:
  hosts:
    test_local_node:
      ansible_host: 192.168.1.37
      ansible_user: dante
      ansible_become_pass: toto
dev:
  hosts:
    dev_docker_1:
      ansible_host: 10.55.1.100
      ansible_user: "guillheu"
      ansible_become_pass: "password"