- hosts: dev
  vars_files:
    - ../configs/node_variables.yaml
  tasks:

  - name: Create avail node script from tempalte
    template:
      dest: /avail/start_avail_node.sh
      src: ../templates/scripts/start_avail_node.sh.j2
    become: yes


  - name: Give execution permissions to avail node script
    file:
      path: /avail/start_avail_node.sh
      mode: 0744
    become: yes

  - name: Downloading chain spec
    get_url:
      url: https://{{avail_node.chainspec_name}}.dataavailability.link/chainspec.raw.json 
      dest: /avail/{{avail_node.chainspec_name}}-chainspec.raw.json
    become: yes

  - name: Create systemd service file
    copy:
      dest: /etc/systemd/system/avail-node.service
      src: ../templates/services/avail-node.service
    become: yes


  - name: Update systemd service
    systemd:
      name: avail-node
      state: started
      enabled: yes
      masked: no
      daemon_reload: yes
    become: yes