- hosts: dev
  vars_files:
    - ../configs/node_variables.yaml
  tasks:
  - name: Downloading chain spec
    get_url:
      url: https://{{avail_node.chainspec_name}}.dataavailability.link/chainspec.raw.json 
      dest: /avail/{{avail_node.chainspec_name}}-chainspec.raw.json
    become: yes

  - name: Create systemd service file
    template:
      dest: /etc/systemd/system/avail-node.service
      src: ../templates/services/avail-node.service.j2
    become: yes


  - name: Update systemd service
    systemd:
      name: avail-node
      state: started
      enabled: yes
      masked: no
      daemon_reload: yes
    become: yes