- hosts: dev
  tasks:
  - name: Create systemd service file
    copy:
      dest: /etc/systemd/system/avail-node.service
      content: |
        [Unit]
        Description=Avail node service
        After=network.target

        [Service]
        Type=simple
        ExecStart=/usr/bin/data-avail --base-path /avail/state --keystore-path /avail/keystore --execution=NativeElseWasm --offchain-worker=Always --enable-offchain-indexing=true --name "guillh_testnode" --chain=/home/dante/avail/misc/genesis/testnet-v3.chain.spec.raw.json --port 30333 --bootnodes="/dns/gateway-fullnode-001.devnet06.dataavailability.link/tcp/30333/p2p/12D3KooWBDBcRhvQdhNY6vJyupZXSRFrG8qUCJtok1xv3oG2uucg" --bootnodes="/dns/gateway-fullnode-002.devnet06.dataavailability.link/tcp/30333/p2p/12D3KooWFNQByvLgK4NtyutLZGmoZeyrShojiKCEkzj8m6YE8teu" --bootnodes="/dns/gateway-fullnode-003.devnet06.dataavailability.link/tcp/30333/p2p/12D3KooWS2UhfueAWeHc71pxHWZFX5g6enuDyJGPWPApkuWe1Lfi"
        Restart=on-failure

        [Install]
        WantedBy=multi-user.target
    become: yes


  - name: Update systemd service
    systemd:
      name: avail-node
      state: started
      enabled: yes
      masked: no
      daemon_reload: yes
    become: yes